version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8001:8001'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local